### ISSUE TITLE
Switching layout modes doesn't always work

### ISSUE THREAD

**Issue by robertlong** [element-hq/element-call#100]
From Andreas:
> sometimes doesn't switch mode when clicking on the button on Desktop; if the bug is present, each click doesn not work

> speaker doesn't focus like on desktop, and toggle switch doesn't work

**Comment by robertlong** [comment]
I was able to reproduce this and I think it was due to a bug when screensharing related exceptions occur. I've fixed [one related issue](https://github.com/vector-im/matrix-video-chat/commit/4debc9e3f56073d1e58569793a59a71ba953112f), but will keep this open as there may be others.

**Comment by robintown** [comment]
This issue is stale, we've switched RTC backends and haven't seen this happen in a long time.
