### ISSUE TITLE
Screenshare changes

### ISSUE THREAD

**Issue by gaelledel** [element-hq/element-call#186]
To implement design changes available here
https://www.figma.com/file/AjvSw4lI9iGO5aTe4WAl4r/?node-id=636%3A84736

**Comment by robertlong** [comment]
Nearly there. Spotlight designs are implemented but freedom still need a bit of work.

**Comment by dbkr** [comment]
@robertlong dod you remember if this got finished or is there still a delta?

**Comment by robintown** [comment]
The designs have changed and this is stale now
