### ISSUE TITLE
Sound effects for join/leave/end/etc

### ISSUE THREAD

**Issue by turt2live** [element-hq/element-call#343]
We should have sound effects for when certain actions happen in the call. imo, at a minimum we should have:
* An audio cue for when someone joins the call (to prevent the awkward case where you're waiting for someone in another tab and they stare at you for a minute before saying hello)
* An audio cue for when someone leaves the call (though potentially become inspired by Jitsi where after a certain size of call the join/leave effects no longer play)
* An audio cue for when you've clicked the hangup button, to give confidence that you've actually left the call and aren't broadcasting your camera to the world still

**Comment by axelsimon** [comment]
Agreed on all counts. Gently helping the user know what's going is good design.

**Comment by nadonomy** [comment]
Huge +1. Having been using Element Call for months now I'm consistently observing people being caught out by the lack of join sound.

**Comment by Half-Shot** [comment]
It's known that "An audio cue for when you've clicked the hangup button" isn't done yet, as it was more complicated than the other options in #2794. I'll create an issue for it.
