### ISSUE TITLE
"double click a feed in freedom layout to focus on it" is not well discoverable

### ISSUE THREAD

**Issue by HarHarLinks** [element-hq/element-call#615]
#### What would you like to do?
focus on a single stream, pinning it into "spotlight" or similar
#### Why would you like to do it?
e.g. to focus on the presenter
#### How would you like to achieve it?
i'm told it's already possible: "double click a feed in freedom layout to focus on it".
however that interaction is not discoverable at all. there needs to be some kind of tooltip.
there should also be a plain button (next to the volume control). perhaps the hint to double click could be built into that somehow.

### Additional context

#613

**Comment by robintown** [comment]
Some random ideas:
- Make it only take one click (the main question is how this affects interactions on mobile)
- Add a hover effect to tiles, such as slightly enlarging them on hover, to make them feel more interactive (I think this same idea is buried somewhere in the designs, even)

**Comment by robintown** [comment]
https://github.com/element-hq/element-call/pull/2325
We removed double-clicking in the interest of focusing on supporting these use cases through spotlight mode and making the latter more usable
