### ISSUE TITLE
Stream towards Firefox die periodically

### ISSUE THREAD

**Issue by dbkr** [element-hq/element-call#803]
### Steps to reproduce

1. Join an SFU call form Firefox
2. Join the same call from chrome
3. Mute & unmute video on chrome

#### What did you expect?
Firefox can see & hear chrome again once chrome unmutes

#### What happened instead?
No audio & frozen frame from chrome -> firefox after chrome unmutes

### Will you send logs?

No

**Comment by dbkr** [comment]
https://github.com/matrix-org/waterfall/issues/106 tracks this in the SFU

**Comment by dbkr** [comment]
Looks like the way (or at least one way) to repro this is to mute and unmute video on the non-firefox side - will update repro steps.

**Comment by dbkr** [comment]
This looks to be more transceiver confusion. EC on Chrome is adding another transceiver when we unmute video, for some reason.

**Comment by dbkr** [comment]
Well, that bug is now fixed in https://github.com/matrix-org/matrix-js-sdk/pull/3144 but this will only have been introduced with my fix to screenshares and we were seeing this bug before that.

**Comment by robintown** [comment]
We're no longer using Waterfall and haven't seen this recently
