### ISSUE TITLE
Overflow menu in fullscreen mode

### ISSUE THREAD

**Issue by dbkr** [element-hq/element-call#807]
The overflow menu doesn't work in fullscreen mode. This is because the popup is being rendered in an overlay container that's outside the maximised element.

**Comment by dbkr** [comment]
#808 removes the button in fullscreen mode.

**Comment by robintown** [comment]
https://github.com/element-hq/element-call/pull/2463 removes full screen mode in the interest of exploring whether an edge-to-edge spotlight tile and the ability to maximize your browser window is enough.
