### ISSUE TITLE
Upgrade dependencies

### ISSUE THREAD

**Issue by dbkr** [element-hq/element-call#896]
### Steps to reproduce

We can't update many of our dependencies at the moment - I tried in https://github.com/vector-im/element-call/pull/893 and it went disastrously:
 * The Vite build started OOMing on github actions with the patch upgrade of 2.9.14 -> 2.9.15
 * Opening any of the menu popups in the app caused a soft crash somewhere in react-aria

### Will you send logs?

Yes

**Comment by robintown** [comment]
We did this (and decided not to touch React ARIA anymore)
