### ISSUE TITLE
Tiles can appear out of the grid layout after ending a screenshare

### ISSUE THREAD

**Issue by dbkr** [element-hq/element-call#960]
### Steps to reproduce

1. Start a screen share
2. Stop screen sharing
3. Video tiles from some people will no longer no aligned to the grid and sitting in random places on the screen

### Will you send logs?

No

**Comment by dbkr** [comment]
Actually we're not sure this is always after ending a screenshare

**Comment by dbkr** [comment]
This will be replaced by the new grid layout code so we might do a timeboxed investigation into this.

**Comment by dbkr** [comment]
Just reproduced this not after a screenshare in our call. The tile is in the right place whilst resizing but once you stop, disappears.

The tile position variables are all correct and so is the CSS value, but chrome isn't applying it correctly. Unchecking & rechecking the translate3d CSS rule puts the tile back into the right place (until you resize again).

In this gif, my tile (top right) disappears entirely after resizing, robin's (bottom left) nudges a few pixels off (it was previously also disappearing entirely before I meddled with the CSS more).

![tilebug](https://github.com/vector-im/element-call/assets/986903/5aef3252-25b9-4d31-94e8-ec49992545fe)

**Comment by robintown** [comment]
https://github.com/element-hq/element-call/pull/2325
